### ISSUE TITLE
NameError: name 'ChangePubKeyEcdsa' is not defined

### ISSUE THREAD

**Issue by imcda** [zksync-sdk/zksync-python#9]
when I try to transfer a coin, I need to unlock the wallet first.

**Comment by StanislavBreadless** [comment]
Hey @imcda ! Please, show us the code snippets that produce the error

**Comment by DryginAlexander** [comment]
Hey! Same issue when trying to follow Python SDK [tutorial](https://zksync.io/api/sdk/python/tutorial.html#unlocking-zksync-account):
```
if not await wallet.is_signing_key_set():
    await wallet.set_signing_key("ETH", eth_auth_data=ChangePubKeyEcdsa())
```
Where can I take ChangePubKeyEcdsa function?

**Comment by StanislavBreadless** [comment]
> Hey @StanislavBreadless! Same issue when trying to follow Python SDK [tutorial](https://zksync.io/api/sdk/python/tutorial.html#unlocking-zksync-account):
> 
> ```
> if not await wallet.is_signing_key_set():
>     await wallet.set_signing_key("ETH", eth_auth_data=ChangePubKeyEcdsa())
> ```
> 
> Where can I take ChangePubKeyEcdsa function?

`from zksync_sdk.types import (ChangePubKeyCREATE2, ChangePubKeyEcdsa)` should work

**Comment by DryginAlexander** [comment]
Thanks, it works
